### ISSUE TITLE
Docker network port forwarding no longer working since latest commit

### ISSUE THREAD

**Issue by ozmodiar** [helderco/docker-php-5.3#4]
Hey

I'm having issues with Docker network port forwarding lately. What I mean by that is that my nginx container is not able to connect to my php-5.3-fpm container on port 9000 anymore. I believe this has something to do with your latest commit: https://github.com/helderco/docker-php-5.3/commit/e616840744a593485cf405dcaf920637d003de6f.

This piece of code makes FPM listen on 127.0.0.1 instead of 0.0.0.0.

> root@14aa0f137728:/var/www/html# netstat -plunt
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
> tcp        0      0 127.0.0.1:9000          0.0.0.0:\*               LISTEN      1/php-fpm.conf)

instead of how it used to be

> root@e9643dcf0d93:/var/www/html# netstat -plunt
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
> tcp6       0      0 :::9000                 :::\*                    LISTEN      1/php-fpm.conf)

I'm not making a pull-request because it is not clear to me why you changed this in the first place, so I don't know if we can just put it back?

Anyway, this is a serious issue that causes the image to be unusable for me for now :-(

Can you take a look at this?

Thanks!

**Comment by helderco** [comment]
Sorry, are you still having this issue?

**Comment by helderco** [comment]
To be clear, the commit before that one introduced a change that made it stop working (ipv6), so that last commit is to return to how it was before.

**Comment by helderco** [comment]
I think you may have been caught in between those two, so let me know if you still have a problem.

**Comment by ozmodiar** [comment]
Hi

I'm sorry but I'm still encountering this issue. My nginx container still cannot reach the php-5.3-fpm container. The following change broke it for me:

```
-    echo 'listen = [::]:9000'; \
+    echo 'listen = 9000'; \
```

Meanwhile, I'm using a fork from your repository that is 2 commits behind and that works perfectly for me... https://github.com/Ozmodiar/docker-php-5.3

**Comment by helderco** [comment]
That can't be the problem @Ozmodiar, the listen directive was only as "[::]:9000" for brief moments, between commits. Look at your fork and see the value for listen. It's the same "listen = 9000" that I have now.

I think your problem has to do with the changes that the official docker repo for php made. I brought those changes to this PHP 5.3 image to be close to how the official repo is structured.

Mainly, some config files got moved to another location or renamed to allow for more configurability (FPM). You shouldn't have a problem unless you're trying to change configuration in this image either from building a new one or from a volume.

Can you confirm that?

**Comment by ozmodiar** [comment]
Hi, you are correct, the listens are the same in both projects so that shouldn't be the problem. I'll look into the configuration changes.

Thanks for the feedback.

**Comment by helderco** [comment]
Now the `php-fpm.conf` file has an `include=etc/php-fpm.d/*.conf` directive, and the _listen_ directive got moved to `php-fpm.d/zz-docker.conf`, which is at the end (sorted alphabetically).

It's in the Dockerfile.

**Comment by stiang** [comment]
I’m having this problem too. Specifically, the nginx container reports "connection refused":

    nginx_1  | 2016/12/15 18:25:55 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: foo.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "foo.dev:9090"

My docker-compose.yml looks like this:

```yaml
version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "9090:80"
    restart: always
    volumes:
      - ./:/code
      - ./support/docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php

  php:
    image: helder/php-5.3
    volumes:
      - ./:/code
      - ./support/docker/php/php.ini:/usr/local/etc/php/conf.d/01-custom.ini
```

It looks like the container is listening on tcp:9000 (`docker exec www_php_1 cat /proc/net/tcp`), and the link appears to be active (`docker inspect www_nginx_1`), so I’m not sure what can be wrong... My docker skills aren’t too strong, though, so I’m probably just looking in the wrong place. Do you have any ideas what could be wrong?

I’d be happy to provide more info/output if it can help!

**Comment by stiang** [comment]
I should add that it works if I change the "image" line in the "php" section of the docker-compose.yml file to `image: php:7-fpm`. The only difference is the php image.

**Comment by stiang** [comment]
Some more information: It seems the new include statements in php-fpm.conf don’t actually work. If I load the old php-fpm.conf where `listen = 9000` is set directly, it works perfectly (meaning it listens on port 9000 for all interfaces, not just 127.0.0.1:9000, which seems to be the default but isn’t enough when linking docker containers together using non-loopback interfaces).

**Comment by helderco** [comment]
Can you get me a simpler reproducible example so I can run? I don't know what you have in `site.conf` and `01-custom.ini`.

**Comment by stiang** [comment]
The 01-custom.ini mount can be skipped, it doesn’t affect the issue. site.conf looks like this:

```
server {
    index index.php index.html;
    server_name foo.dev;
    root /code;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```

**Comment by helderco** [comment]
I'll see what's going on with the `helder/php-5.3` when I get the chance. In the meantime, you can try my more enhanced `helder/php:5.3` image, which is what I normally use:

```
version: '2'
services:
  nginx:
    image: helder/nginx
    ports:
      - "9090:80"
    depends_on:
      - php
    volumes:
      - ./:/usr/src/app
    environment:
      - CONF_APP=php
      - CONF_UPSTREAM=php:9000

  php:
    image: helder/php:5.3
    volumes:
      - ./:/usr/src/app
```
